#!/usr/bin/env bash
# shellcheck disable=SC2154

# Install nginx
apt-get update -y
apt-get install -y nginx

# Create default page
echo "Hello World!" > /var/www/html/index.html

# Add custom header to nginx configuration
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    add_header X-Served-By \$hostname;
}
EOF

# Restart nginx
systemctl restart nginx
systemctl enable nginx
