#!/usr/bin/env bash
# Installs and configures Nginx with a custom X-Served-By HTTP response header.
# shellcheck disable=SC2154

apt-get update -y
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    add_header X-Served-By \$hostname;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

systemctl enable nginx
systemctl restart nginx
