#!/usr/bin/env bash
# Installs and configures Nginx with a custom X-Served-By HTTP response header.
# shellcheck disable=SC2154

apt-get update -y
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

if ! grep -q "X-Served-By" /etc/nginx/sites-available/default; then
    sed -i '/server_name _;/a\
    add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
fi

systemctl restart nginx
systemctl enable nginx
