#!/usr/bin/env bash
# Installs and configures Nginx on an Ubuntu server
apt-get update
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html

service nginx restart
