#!/usr/bin/env bash
# Configures Nginx and sets up a 301 redirect

apt-get update -y
apt-get install nginx -y

# Default page
echo "Holberton School for the win!" > /var/www/html/index.html

# Configure Nginx
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Check configuration and restart Nginx
nginx -t && service nginx restart
