#!/usr/bin/env bash
# Configure Nginx with a custom 404 page and redirect

apt-get update -y
apt-get install nginx -y

# Default page
echo "Holberton School for the win!" > /var/www/html/index.html

# Custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Add redirect and custom 404 configuration
sed -i '/index index.html index.nginx-debian.html;/a\
\
    error_page 404 /404.html;\
\
    location = /404.html {\
        internal;\
    }\
\
    location /redirect_me {\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
    }' /etc/nginx/sites-available/default

# Test configuration
nginx -t

# Restart Nginx
service nginx restart
